### PR TITLE
PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by swordfox**

### CODE REVIEW

**Comment by DorsetDigital** [comment]
Thanks for the PR.    I was curious about the addition of the ternary operation on the body variable.    What's the issue in 
 PHP8.1 that fixes?
 
 Cheers
 Tim

**Comment by swordfox** [comment]
> 

Hey Tim,

See below error that it threw:

```
[Deprecated] str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
GET /dev/build
Line 154 in /vendor/dorsetdigital/silverstripe-cdnrewrite/src/CDNMiddleware.php
```

I'm not sure if what I have done is the best way to fix the issue but it works.

Cheers

**Comment by DorsetDigital** [comment]
Ah, interesting.  I didn't think there would be a situation when the body would be null.
Would you mind updating your PR to add the same functionality to the `addPrefetch()` function as well?   I figure that would throw the same warning if the body is null and prefetch tags are active.

**Comment by swordfox** [comment]
Hey Tim,

I've done quite a few tests and weirdly it only throws an error for `rewriteTags()` and only when doing `dev/build`.

Cheers

**Comment by DorsetDigital** [comment]
I have rolled some of this functionality into a wider update/release which should fix the underlying issue.  Thanks for the assistance!

**Pull request closed without merging**
